export type ArtWork = {
  id: number;
  name: string;
  type: string;
  size: string;
  url: string;
  medium: string;
  uri: string;
  show?: boolean;
};

export const WorkTypes = {
  portrait: "portraits",
  landscape: "landscapes",
  charcoal: "charcoals",
  stillLife: "still life",
};

export const works: ArtWork[] = [
  {
    id: 1,
    name: "Fluffy Flowers",
    uri: "fluffy-flowers",
    type: WorkTypes.landscape,
    size: "60cm x 60cm",
    url: "im1.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 2,
    name: "Kitchen and me",
    uri: "kitchen-and-me",
    type: WorkTypes.portrait,
    size: "40cm x 60cm",
    url: "im2.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 3,
    name: "Affordable Insulation",
    uri: "affordable-insulation",
    type: WorkTypes.portrait,
    size: "40cm x 60cm",
    url: "im3.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 4,
    name: "Autumn in Wythenshawe",
    uri: "autumn-in-wythenshawe",
    type: WorkTypes.landscape,
    size: "60cm x 40cm",
    url: "im4.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 5,
    name: "Seaworms and me",
    uri: "seaworms-and-me",
    type: WorkTypes.portrait,
    size: "40cm x 60cm",
    url: "im5.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 6,
    name: "Lobsang and coloured shapes",
    uri: "lobsang-and-coloured-shapes",
    type: WorkTypes.portrait,
    size: "60cm x 60cm",
    url: "im6.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 7,
    name: "Old curtain and me",
    uri: "old-curtain-and-me",
    type: WorkTypes.portrait,
    size: "40cm x 60cm",
    url: "im7.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 8,
    name: "Echo in the bedroom",
    uri: "echo-in-the-bedroom",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im8.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 9,
    name: "Cliffs Carlin How",
    uri: "cliffs-carlin-how",
    type: WorkTypes.landscape,
    size: "30cm x 30cm",
    url: "im9.jpg",
    medium: "Acrylic on board",
    show: true,
  },
  {
    id: 10,
    name: "View from the window",
    uri: "view-from-the-window",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im10.jpg",
    medium: "Acrylic on paper",
    show: true,
  },
  {
    id: 11,
    name: "Tulips",
    uri: "tulips",
    type: WorkTypes.stillLife,
    size: "40cm x 60cm",
    url: "im11.jpg",
    medium: "Acrylic on paper",
    show: true,
  },
  {
    id: 12,
    name: "Ruby",
    uri: "ruby",
    type: WorkTypes.charcoal,
    size: "30cm x 40cm",
    url: "im12.jpg",
    medium: "Charcoal on paper",
    show: true,
  },
  {
    id: 13,
    name: "Houses on the hill",
    uri: "houses-on-the-hill",
    type: WorkTypes.landscape,
    size: "90cm x 90cm",
    url: "im13.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 14,
    name: "House on the hill",
    uri: "house-on-the-hill",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im14.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 15,
    name: "Mum",
    uri: "mum",
    type: WorkTypes.charcoal,
    size: "30cm x 40cm",
    url: "im15.jpg",
    medium: "Charcoal on paper",
    show: true,
  },
  {
    id: 16,
    name: "Person",
    uri: "person",
    type: WorkTypes.charcoal,
    size: "30cm x 40cm",
    url: "im16.jpg",
    medium: "Charcoal on paper",
    show: true,
  },
  {
    id: 17,
    name: "Person two",
    uri: "person-two",
    type: WorkTypes.charcoal,
    size: "30cm x 40cm",
    url: "im17.jpg",
    medium: "Charcoal on paper",
    show: true,
  },
  {
    id: 18,
    name: "Person four",
    uri: "person-four",
    type: WorkTypes.charcoal,
    size: "30cm x 40cm",
    url: "im18.jpg",
    medium: "Charcoal on paper",
    show: true,
  },
  {
    id: 19,
    name: "Person five",
    uri: "person-five",
    type: WorkTypes.charcoal,
    size: "30cm x 40cm",
    url: "im19.jpg",
    medium: "Charcoal on paper",
    show: true,
  },
  {
    id: 20,
    name: "Person six",
    uri: "person-six",
    type: WorkTypes.charcoal,
    size: "30cm x 40cm",
    url: "im20.jpg",
    medium: "Charcoal on paper",
    show: true,
  },
  {
    id: 21,
    name: "Person seven",
    uri: "person-seven",
    type: WorkTypes.charcoal,
    size: "30cm x 40cm",
    url: "im21.jpg",
    medium: "Charcoal on paper",
    show: true,
  },
  {
    id: 22,
    name: "Wild flowers",
    uri: "wild-flowers",
    type: WorkTypes.landscape,
    size: "50cm x 60cm",
    url: "im22.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 23,
    name: "Wild flowers v2",
    uri: "wild-flowers-v2",
    type: WorkTypes.landscape,
    size: "60cm x 60cm",
    url: "im23.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 24,
    name: "Cath Carlin",
    uri: "cath-carlin",
    type: WorkTypes.portrait,
    size: "40cm x 60cm",
    url: "im24.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 25,
    name: "Ruby v2",
    uri: "ruby-v2",
    type: WorkTypes.portrait,
    size: "40cm x 60cm",
    url: "im25.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 26,
    name: "Cliff Skinningrove",
    uri: "cliff-skinningrove",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im26.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 27,
    name: "Carlin How",
    uri: "carlin-how",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im27.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 28,
    name: "Carlin How v2",
    uri: "carlin-how-v2",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im28.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 29,
    name: "Carlin How v3",
    uri: "carlin-how-v3",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im29.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 30,
    name: "Carlin How v4",
    uri: "carlin-how-v4",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im30.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 31,
    name: "Carlin How v5",
    uri: "carlin-how-v5",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im31.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 32,
    name: "Wythenshawe",
    uri: "wythenshawe",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im32.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 33,
    name: "Saltburn",
    uri: "saltburn",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im33.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 34,
    name: "Carlin How v7",
    uri: "carlin-how-v7",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im34.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 35,
    name: "Carlin How v8",
    uri: "carlin-how-v8",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im35.jpg",
    medium: "Acrylic on paper",
    show: true,
  },
  {
    id: 36,
    name: "Carlin How v9",
    uri: "carlin-how-v9",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im36.jpg",
    medium: "Acrylic on paper",
    show: true,
  },
  {
    id: 37,
    name: "Carlin How v10",
    uri: "carlin-how-v10",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im37.jpg",
    medium: "Acrylic on paper",
    show: true,
  },
  {
    id: 38,
    name: "Carlin How v11",
    uri: "carlin-how-v11",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im38.jpg",
    medium: "Acrylic on paper",
    show: true,
  },
  {
    id: 39,
    name: "Carlin How v12",
    uri: "carlin-how-v12",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im39.jpg",
    medium: "Acrylic on paper",
    show: true,
  },
  {
    id: 40,
    name: "Carlin How v13",
    uri: "carlin-how-v13",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im40.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
  {
    id: 41,
    name: "Carlin How v14",
    uri: "carlin-how-v14",
    type: WorkTypes.landscape,
    size: "40cm x 30cm",
    url: "im41.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
   {
    id: 42,
    name: "Flowers v2",
    uri: "flowers-v2",
    type: WorkTypes.stillLife,
    size: "30cm x 40cm",
    url: "im42.jpg",
    medium: "Acrylic on canvas",
    show: true,
  },
];

export const getWorksByType = (workType: string) => {
  return works.filter((obj) => obj.type === workType).map((obj) => obj);
};

export const getAllWorks = () => {
  return works;
};

export const getWorkByUri = (workUri: string) => {
  return works.find((obj) => obj.uri === workUri);
};

export const makeUri = (name: string): string => {
  return name.trim().replace(/\s+/g, "-").toLowerCase();
};
